spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/Nova
#    username: sa
#    password:
#    dirver-class-name: org.h2.Driver
#    # spring data jpa ??
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        #        show_sql: true
#        format_sql: true
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.2:3306/novadb?allowedPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username:
    password:

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            redirectUri: http://ec2-52-79-189-183.ap-northeast-2.compute.amazonaws.com:8081/oauth2/callback/google
            scope:
              - email
              - profile


          github:
            clientId:
            clientSecret:
            redirectUri: http://localhost:8081/oauth2/callback/github
            scope:
              - user:email
              - read:user


# cors
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

## jwt secret key ??
jwt.secret:

# ?? ?? secret Key ? RedirectUri ??

app:
  auth:
    tokenSecret:
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect
server:
  port: 8081