spring:
  config:
    activate:
      on-profile: h2

  datasource:
    url: jdbc:h2:tcp://localhost/~/Nova
    username: sa
    password:
    dirver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            redirectUri:
            scope:
              - email
              - profile

          github:
            clientId:
            clientSecret:
            redirectUri:
            scope:
              - user:email
              - read:user

# cors ??
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key ??
jwt.secret:

# ?? ?? secret Key ? RedirectUri ??
app:
  auth:
    tokenSecret:
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect
server:
  port: 8081